### ISSUE TITLE
Show error on user articles page if there's none of them

### ISSUE THREAD

**Issue by webknjaz** [itkpi/journey#4]
existing user: http://blog.itkpi.pp.ua/author/webknjaz/ HTTP 500
non-existing user: http://blog.itkpi.pp.ua/author/w/ in body "sql: no rows in result set"

**Comment by rrader** [comment]
bug with existing user fixed.
non-existing user is the framework-wide issue:
"sql: no rows in result set" is showing on every 404 page. Should be fixed outside of the author pages scope.
